# Generated by Django 4.2.11 on 2024-04-15 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Duxu1000009',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driverID', models.CharField(max_length=100)),
                ('carPlateNumber', models.CharField(max_length=100)),
                ('unix_Time', models.BigIntegerField()),
                ('speed', models.FloatField()),
                ('isOverspeed', models.IntegerField()),
            ],
            options={
                'db_table': 'duxu1000009',
            },
        ),
        migrations.CreateModel(
            name='Hanhui1000002',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driverID', models.CharField(max_length=100)),
                ('carPlateNumber', models.CharField(max_length=100)),
                ('unix_Time', models.BigIntegerField()),
                ('speed', models.FloatField()),
                ('isOverspeed', models.IntegerField()),
            ],
            options={
                'db_table': 'hanhui1000002',
            },
        ),
        migrations.CreateModel(
            name='Haowei1000008',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driverID', models.CharField(max_length=100)),
                ('carPlateNumber', models.CharField(max_length=100)),
                ('unix_Time', models.BigIntegerField()),
                ('speed', models.FloatField()),
                ('isOverspeed', models.IntegerField()),
            ],
            options={
                'db_table': 'haowei1000008',
            },
        ),
        migrations.CreateModel(
            name='Likun1000003',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driverID', models.CharField(max_length=100)),
                ('carPlateNumber', models.CharField(max_length=100)),
                ('unix_Time', models.BigIntegerField()),
                ('speed', models.FloatField()),
                ('isOverspeed', models.IntegerField()),
            ],
            options={
                'db_table': 'likun1000003',
            },
        ),
        migrations.CreateModel(
            name='Panxian1000005',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driverID', models.CharField(max_length=100)),
                ('carPlateNumber', models.CharField(max_length=100)),
                ('unix_Time', models.BigIntegerField()),
                ('speed', models.FloatField()),
                ('isOverspeed', models.IntegerField()),
            ],
            options={
                'db_table': 'panxian1000005',
            },
        ),
        migrations.CreateModel(
            name='Shenxian1000004',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driverID', models.CharField(max_length=100)),
                ('carPlateNumber', models.CharField(max_length=100)),
                ('unix_Time', models.BigIntegerField()),
                ('speed', models.FloatField()),
                ('isOverspeed', models.IntegerField()),
            ],
            options={
                'db_table': 'shenxian1000004',
            },
        ),
        migrations.CreateModel(
            name='Summary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driverID', models.CharField(max_length=100)),
                ('carPlateNumber', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('number_of_overspeed', models.IntegerField()),
                ('total_overspeed', models.IntegerField()),
                ('number_of_fatigueDriving', models.IntegerField()),
                ('number_of_neutralSlide', models.IntegerField()),
                ('total_neutralSlideTime', models.IntegerField()),
            ],
            options={
                'db_table': 'summary',
            },
        ),
        migrations.CreateModel(
            name='Xiexiao1000001',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driverID', models.CharField(max_length=100)),
                ('carPlateNumber', models.CharField(max_length=100)),
                ('unix_Time', models.BigIntegerField()),
                ('speed', models.FloatField()),
                ('isOverspeed', models.IntegerField()),
            ],
            options={
                'db_table': 'xiexiao1000001',
            },
        ),
        migrations.CreateModel(
            name='Xiezhi1000006',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driverID', models.CharField(max_length=100)),
                ('carPlateNumber', models.CharField(max_length=100)),
                ('unix_Time', models.BigIntegerField()),
                ('speed', models.FloatField()),
                ('isOverspeed', models.IntegerField()),
            ],
            options={
                'db_table': 'xiezhi1000006',
            },
        ),
        migrations.CreateModel(
            name='Zengpeng1000000',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driverID', models.CharField(max_length=100)),
                ('carPlateNumber', models.CharField(max_length=100)),
                ('unix_Time', models.BigIntegerField()),
                ('speed', models.FloatField()),
                ('isOverspeed', models.IntegerField()),
            ],
            options={
                'db_table': 'zengpeng1000000',
            },
        ),
        migrations.CreateModel(
            name='Zouan1000007',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driverID', models.CharField(max_length=100)),
                ('carPlateNumber', models.CharField(max_length=100)),
                ('unix_Time', models.BigIntegerField()),
                ('speed', models.FloatField()),
                ('isOverspeed', models.IntegerField()),
            ],
            options={
                'db_table': 'zouan1000007',
            },
        ),
    ]
