# Generated by Django 4.2.11 on 2024-04-17 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DriveData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driverID', models.CharField(max_length=100)),
                ('carPlateNumber', models.CharField(max_length=100)),
                ('unix_Time', models.BigIntegerField()),
                ('speed', models.FloatField()),
                ('isOverspeed', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Summary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driverID', models.CharField(max_length=100)),
                ('carPlateNumber', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('number_of_overspeed', models.IntegerField()),
                ('total_overspeed', models.IntegerField()),
                ('number_of_fatigueDriving', models.IntegerField()),
                ('number_of_neutralSlide', models.IntegerField()),
                ('total_neutralSlideTime', models.IntegerField()),
            ],
            options={
                'db_table': 'summary',
            },
        ),
    ]
