# Generated by Django 4.2.11 on 2024-04-17 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='drivedata',
            table='drivedata',
        ),
    ]
